# conda_env.yml
# Configuration file for creating a Conda Environment with dependencies needed
# for Danesfield.
# Create the environment by running (after installing Miniconda):
#   $ conda env create -f conda_env.yml
# then:
# source activate core3d-dev
#

---
name: core3d-dev

channels:
  # - local
  - conda-forge/label/cf202003
  - defaults
  - pytorch

dependencies:
  # - vtk
  # - liblas
  # - pcl
  # - python-pcl
  # - texture-atlas
  # - core3d-purdue
  # - core3d-tf_ops
  # - pubgeo-tools
  # - pubgeo-core3d-metrics
  # repeat dependencies of built packages
  - cmake
  - ninja
  - boost-cpp
  - tensorflow-gpu=1.14
  - python
  - libgdal
  - pdal
  - geotiff
  - flann
  - eigen
  - qhull
  - cython=0.25
  - numpy
  - pkg-config
  - nose
  - filelock
  - opencv
  - cgal
  - laspy
  - matplotlib
  - scipy
  - jsonschema
  # end repeat
  - pyproj
  - flake8
  - pytest
  - pytorch-gpu
  - scikit-learn
  - scikit-image
  - xorg-libsm
  - xorg-libX11
  - pip
  - pip:
      - ubelt
      - plyfile
      - open3d-python
  - torchvision
  - tqdm
  - requests
