package:
    name: kwiver
    version: 1.4.5
source:
    git_url: https://github.com/Kitware/kwiver.git
    git_rev: 09e587e69ae55624ddea9193420cc37c8c11403d

build:
    number: 1

requirements:
    build:
        - cmake 3.18
        - ninja
        - numpy
        - six
        - python {{ python }}
        - eigen
        - pybind11

    run:
        - python {{ python }}
        - numpy
        - eigen
        - pybind11

about:
    home: https://www.kwiver.org/
    license_file: LICENSE
    summary: A collection of software tools designed to tackle
     image and video analysis problems and other related challenges.
extra:
    copy_test_source_files: true
    final: true
